### PR TITLE
Pattern C# 7.0 - 11.0

### LINKED ISSUE #13: C#7: 'switch' statement patterns
Design document: https://github.com/dotnet/csharplang/blob/master/proposals/patterns.md

### LINKED ISSUE #14: C#7: 'is' expression patterns
Design document: https://github.com/dotnet/csharplang/blob/master/proposals/patterns.md

### LINKED ISSUE #173: C# 8.0 switch expression syntax highlighting not working
- VSCode 1.41.1
- OS: Windows 10 Pro
- Theme: Atom One Light

Steps to reproduce:
- Enter the following C# code:

```csharp
private Color NumberToColor(int number) => number switch // switch is not highlighted
{
     var x when x < 10 => Color.Blue, // var, when and Color are not highlighted
     _ => Color.Red // Same here
};
```

- Syntax highlighting is not correct:
image

_This problem occurs even when all extensions are disabled_

### PR DESCRIPTION
**Pull request by wise0704**
### References:

- [C# 7.0 - Patterns](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/patterns#112-pattern-forms)
- [C# 8.0 - Recursive Pattern Matching](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/patterns#detailed-design)
- [C# 9.0 - Pattern matching enhancements](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/patterns3)
- [C# 10.0 - Extended property patterns](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/extended-property-patterns#detailed-design)
- [C# 11.0 - List patterns](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/list-patterns#detailed-design)

### Combined grammar from 7.0-11.0:

<details>
<summary>ANTLR</summary>

```antlr
pattern
    : disjunctive_pattern
    ;
disjunctive_pattern
    : disjunctive_pattern 'or' conjunctive_pattern
    | conjunctive_pattern
    ;
conjunctive_pattern
    : conjunctive_pattern 'and' negated_pattern
    | negated_pattern
    ;
negated_pattern
    : 'not' negated_pattern
    | primary_pattern
    ;
primary_pattern
    : parenthesized_pattern
    | relational_pattern
    | constant_pattern
    | declaration_pattern
    | var_pattern
    | type_pattern
    | positional_pattern
    | property_pattern
    | discard_pattern
    | list_pattern
    | slice_pattern
    ;
parenthesized_pattern
    : '(' pattern ')'
    ;
relational_pattern
    : '<' relational_expression
    | '<=' relational_expression
    | '>' relational_expression
    | '>=' relational_expression
    ;
constant_pattern
    : constant_expression
    ;
declaration_pattern
    : type simple_designation
    ;
var_pattern
    : 'var' designation
    ;
type_pattern
    : type
    ;
positional_pattern
    : type? '(' subpatterns? ')' property_subpattern? simple_designation?
    ;
subpatterns
    : subpattern
    | subpattern ',' subpatterns
    ;
subpattern
    : pattern
    : subpattern_name ':' pattern
    ;
subpattern_name
    : identifier 
    | subpattern_name '.' identifier
    ;
property_subpattern
    : '{' '}'
    | '{' subpatterns ','? '}'
    ;
property_pattern
    : type? property_subpattern simple_designation?
    ;
simple_designation
    : single_variable_designation
    | discard_designation
    ;
discard_pattern
    : '_'
    ;
list_pattern
    : '[' (pattern (',' pattern)* ','?)? ']' simple_designation?
    ;
slice_pattern
    : '..' pattern?
    ;
```

</details>

### Note:

Everything should work regardless of line breaks or whitespaces.
One problem is there's no way to differentiate `x is int? a` and `x is int ? a : b` while fully supporting line breaks.
Current solution is to assume no whitespace before `?` means nullable, and conditional statement otherwise.

### Todo:

- Implementation
  - [x] Pattern combinators
  - [x] ~~`parenthesized_pattern`~~ &rarr; not implemented &mdash; unable to distinguish the begin token `(` from `positional_subpattern`, but fortunately `positional_subpattern` is a superset of `parenthesized_pattern` (pattern within parentheses)
  - [x] `relational_pattern`
  - [x] `constant_pattern`
  - [x] `declaration_pattern`
  - [x] `var_pattern`
  - [x] `type_pattern` &rarr; ~~use different logic from other type detections to allow line breaks~~, ~~figure out what to do with question mark~~
  - [x] `positional_pattern`
  - [x] `property_pattern`
  - [x] `discard_pattern`
  - [x] `list_pattern`
  - [x] `slice_pattern`
  - [x] `is` operator
  - `switch` statement
    - [x] `case` label
    - [x] `when` clause
  - `switch` expression
    - [x] pattern arm
    - [x] `when` clause
- [x] Existing tests pass
- Add new tests
  - `is` operator
    - [x] All patterns
  - `switch` statement
    - [x] All patterns
    - [x] `when` clause
  - `switch` expression
    - [x] All patterns
    - [x] `when` clause

Resolves #13, resolves #14, resolves #173
Related: #239

### CODE REVIEW

**Comment by wise0704** [comment]
image

I don't feel like writing tests to all these features they piled up over the years...

**Comment by wise0704** [comment]
Quick question @JoeRobich
Why is .json the only file that's ignored? The other two files are also just outputs.
https://github.com/dotnet/csharp-tmLanguage/blob/2759f6d64fff1bfb35e1e23df78fda373e7de3e7/.gitignore#L4

**Comment by JoeRobich** [comment]
> Why is .json the only file that's ignored?

We should probably stop writing one out. The VS Code repo generates their own from our source. If it is actually useful to you, we should update the gulp script to stop trying to write the extra information that VS Code adds to their copy.

File: test/utils/tokenize.ts [hunk 1]
```diff
@@ -482,6 +482,12 @@ export namespace Token {
             export const GreaterThanOrEqual = createToken('>=', 'keyword.operator.relational.cs');
         }
 
+        export namespace Word {
```
Comment (JoeRobich) [inline test/utils/tokenize.ts:485]: Would `Pattern` work better here? Is it time to move `is` from being a normal keyword to being an operator?

Comment (wise0704) [reply test/utils/tokenize.ts:485]: > Is it time to move is from being a normal keyword to being an operator?

I guess it makes sense. Both `as` and `is` are more of an operator compared to other keywords.

I was also wondering how specific we want to define the scopes. Whether we prefer

```
keyword.operator.word.as.cs
keyword.operator.word.is.cs
keyword.operator.word.and.cs
keyword.operator.word.or.cs
keyword.operator.word.not.cs
```

or we want more details

```
keyword.operator.word.cast.as.cs
keyword.operator.word.pattern.is.cs
keyword.operator.word.pattern.combinator.and.cs
keyword.operator.word.pattern.combinator.or.cs
keyword.operator.word.pattern.combinator.not.cs
```

File: src/csharp.tmLanguage.yml [hunk 2]
```diff
@@ -3066,7 +3120,6 @@ repository:
       '7': { name: entity.name.variable.parameter.cs }
 
   type:
-    name: meta.type.cs
```
Comment (wise0704) [inline src/csharp.tmLanguage.yml:3069]: By the way, although this is somewhat unrelated to the PR, I removed this line because `meta.` scope is meant to be for definition bodies.

`meta.type` is meant to be used for the class body starting from and including `public/internal class ... {` to the closing brace `}`.

File: test/utils/tokenize.ts (hunk 1 above)
Comment (JoeRobich) [reply test/utils/tokenize.ts:485]: Personally, I like the more specific set. Does `word` add anything here though?

File: src/csharp.tmLanguage.yml (hunk 2 above)
Comment (JoeRobich) [reply src/csharp.tmLanguage.yml:3069]: Sounds good. Thanks!

**Comment by JoeRobich** [comment]
> I don't feel like writing tests to all these features they piled up over the years...

I opened a PR to add some tests to your branch. https://github.com/wise0704/csharp-tmLanguage/pull/1

File: test/utils/tokenize.ts (hunk 1 above)
Comment (wise0704) [reply test/utils/tokenize.ts:485]: Yes, because `keyword.operator` is for symbols and is coloured grey/white in most themes.

`keyword.operator.word` is chosen for word operators (for example, in python) and in most themes is coloured the same as normal keywords (blue in many themes).

Comment (JoeRobich) [reply test/utils/tokenize.ts:485]: That makes sense. I think we should go with the specific set.

**Comment by wise0704** [comment]
`type-pattern` now supports line breaks, but:

> One problem is there's no way to differentiate `x is int? a` and `x is int ? a : b` while fully supporting line breaks.
Current solution is to assume no whitespace before `?` means nullable, and conditional statement otherwise.

**Review by JoeRobich — APPROVED** [review]
This is a massive improvement. Thanks @wise0704!

File: test/utils/tokenize.ts (hunk 1 above)
Comment (wise0704) [reply test/utils/tokenize.ts]: @JoeRobich I noticed that `keyword.operator.word` is not set in the default themes of vscode:

```json
"scope": [
  "keyword.operator.new",
  "keyword.operator.expression",
  "keyword.operator.cast",
  "keyword.operator.sizeof",
  "keyword.operator.alignof",
  "keyword.operator.typeid",
  "keyword.operator.alignas",
  "keyword.operator.instanceof",
  "keyword.operator.logical.python",
  "keyword.operator.wordlike"
],
```

What would be a better fit for the pattern keywords then? C#'s old "is-type operator" would've been okay to be assigned to `keyword.operator.instanceof`, but now the `is` keyword strictly only takes patterns (type is merged into a type pattern) - and then there are also 3 extra keywords `and or not`.

If we just use `keyword.operator.pattern`, then people might complain that their `is` keyword is now suddenly not working (highlighted grey).

Comment (JoeRobich) [reply test/utils/tokenize.ts]: Looking at other grammars, it seems that cpp emits both `keyword.operator.wordlike` then a specific operator scope like `keyword.operator.pattern.is`

https://github.com/microsoft/vscode/blob/b4cf1fa6029f3b05413a7c28b89971288a7b9f08/extensions/cpp/syntaxes/cpp.tmLanguage.json#L16465-L16472

Comment (wise0704) [reply test/utils/tokenize.ts]: Personally I don't like that solution. It's unnecessary to have two scopes assigned when they could just be merged and have the same customisation levels. For example, `keyword.operator.wordlike.pattern.is` achieves the same. The only downside is that it's kinda too long?

Currently, the options I have in mind are:
* `keyword.operator.wordlike.pattern.*` &mdash; current approach, just `word` &rarr; `wordlike`
* `keyword.pattern.*` &mdash; shorter approach, would be treated as a `keyword` as themes won't have this scope yet
* `keyword.operator.pattern.*` &mdash; would be best if we could have this, but themes don't have this set yet and will appear grey (operator) and would appear to users as if highlighting doesn't work

Comment (JoeRobich) [reply test/utils/tokenize.ts]: I like the first option because it works today and aligns with what other grammars are doing.
